### ISSUE TITLE
Issue with the newest Rats version

### ISSUE THREAD

**Issue by moninformateur** [Aureljz/Towers-of-the-Wild-Additions#8]
When launching the game with the new Rats [1.20-8.1](https://legacy.curseforge.com/minecraft/mc-mods/rats/files/4785586), I get a crash.

[Here's the link to the mclo.gs log](https://mclo.gs/tiKm0ke)

Log error is ... 
```
Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod totw_modded only supports rats 8.0.6 or above
Currently, rats is 1.20.1-8.1
```

**Comment by Aureljz** [comment]
This mod isn't totw_modded. This is totw_additions.

**Comment by moninformateur** [comment]
My bad, bad Google result indeed.
